### ISSUE TITLE
색깔을 선택했을 선택이 됐다고 테두리로 보여주는 건 어떤가요?

### ISSUE THREAD

**Issue by arkk200** [minseok0415/PIXEL#1]
선택을 안했을 때

<img width="49" alt="스크린샷 2023-06-14 오후 7 19 14" src="https://github.com/minseok0415/PIXEL/assets/102217839/42a2554a-7c79-4360-9303-26c48c70350e">

선택을 했을 때

<img width="53" alt="스크린샷 2023-06-14 오후 7 19 06" src="https://github.com/minseok0415/PIXEL/assets/102217839/e72b5f99-fabc-4b6a-ab22-aa8358fb9187">

**Comment by minseok0415** [comment]
했슴미다^^
